services:
  - type: web
    name: bolagsplatsen-scraper-api
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SCRAPY_SETTINGS_MODULE
        value: bolagsplatsen_scraper.settings
      - key: PIP_NO_CACHE_DIR
        value: "1"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "requirements.txt"
        - "render.yaml"
        - "bolagsplatsen_scraper/**"
